# permissions for end users to view configbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configbuild-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-configbuilder
    app.kubernetes.io/part-of: kube-configbuilder
    app.kubernetes.io/managed-by: kustomize
  name: configbuild-viewer-role
rules:
- apiGroups:
  - configbuilder.puiterwijk.org
  resources:
  - configbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configbuilder.puiterwijk.org
  resources:
  - configbuilds/status
  verbs:
  - get
