# permissions for end users to view fieldforges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fieldforge-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-fieldforge
    app.kubernetes.io/part-of: kube-fieldforge
    app.kubernetes.io/managed-by: kustomize
  name: fieldforge-viewer-role
rules:
- apiGroups:
  - fieldforge.puiterwijk.org
  resources:
  - fieldforges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fieldforge.puiterwijk.org
  resources:
  - fieldforges/status
  verbs:
  - get
