---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - fieldforge.puiterwijk.org
  resources:
  - fieldforges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fieldforge.puiterwijk.org
  resources:
  - fieldforges/finalizers
  verbs:
  - update
- apiGroups:
  - fieldforge.puiterwijk.org
  resources:
  - fieldforges/status
  verbs:
  - get
  - patch
  - update
