---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - configbuilder.puiterwijk.org
  resources:
  - configbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configbuilder.puiterwijk.org
  resources:
  - configbuilds/finalizers
  verbs:
  - update
- apiGroups:
  - configbuilder.puiterwijk.org
  resources:
  - configbuilds/status
  verbs:
  - get
  - patch
  - update
