apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kube-fieldforge.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: FieldForge is the Schema for the fieldforges API
      displayName: Field Forge
      kind: FieldForge
      name: fieldforges.fieldforge.puiterwijk.org
      statusDescriptors:
      - description: Conditions store the status conditions of the FieldForge instances
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: FieldForge operator builds ConfigMaps and Secrets from other sources
  displayName: FieldForge
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - configmap
  - secret
  links:
  - name: Kube FieldForge
    url: https://github.com/kube-fieldforge/kube-fieldforge
  maintainers:
  - email: patrick@puiterwijk.org
    name: Patrick Uiterwijk
  maturity: alpha
  minKubeVersion: 1.16.0
  provider:
    name: Patrick Uiterwijk
    url: https://github.com/kube-fieldforge
  version: 0.0.1
