apiVersion: fieldforge.puiterwijk.org/v1alpha1
kind: FieldForge
metadata:
  name: fieldforge-sample
spec:
  target:
    kind: ConfigMap
    name: built-cm
  annotations:
    test_constant:
      type: constant
      constant:
        value: someannotation
  labels:
    test_label:
      type: constant
      constant:
        value: somelabel
  stringData:
    string_constant:
      type: constant
      constant:
        value: someconstant
    string_from_cm:
      type: configmap
      configMap:
        name: cm-test
        key: cm_test_string
    string_from_secret:
      type: secret
      secret:
        name: secret-test
        key: secret_test_string
  binaryData:
    binary_from_cm:
      type: configmap
      configMap:
        name: cm-test
        key: cm_test_binary
    binary_from_secret:
      type: secret
      secret:
        name: secret-test
        key: secret_test_binary